In [18]:
import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X_centered = X - X.mean(axis = 0)
u,s,vt = np.linalg.svd(X_centered)
c1 = vt.T[:,0]
c2 = vt.T[:,1]

In [19]:
W2 = vt.T[:,:2]
X2D = X_centered.dot(W2)

In [20]:
print(X2D)

[[-5.19615242e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.19615242e+00  1.33226763e-15]]


In [21]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X2D = pca.fit_transform(X)


In [22]:
print(X2D)

[[-5.19615242e+00  5.55006974e-17]
 [ 0.00000000e+00 -0.00000000e+00]
 [ 5.19615242e+00  5.55006974e-17]]


In [23]:
pca.explained_variance_ratio_

array([1.000000e+00, 1.140862e-34])

In [1]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml("mnist_784",version=1)
X = mnist["data"]
y = mnist["target"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)


In [3]:
from sklearn.decomposition import PCA
pca = PCA(n_components=154)
X_reduced = pca.fit_transform(X_train)
pca_recovered = pca.inverse_transform(X_reduced)

In [4]:
rnd_pca = PCA(n_components=154,svd_solver="randomized")
X_reduced = rnd_pca.fit_transform(X_train)

In [6]:
import numpy as np
from sklearn.decomposition import IncrementalPCA
n_batches = 100
inc_pca = IncrementalPCA(n_components=154)
for X_batch in np.array_split(X_train,n_batches):
    inc_pca.partial_fit(X_batch)
X_reduced = inc_pca.transform(X_train)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)


In [ ]:
from sklearn.decomposition import KernelPCA
rbf_pca = KernelPCA(n_components=2,kernel="rbf",gamma=0.04)
X_reduced = rbf_pca.fit_transform(X)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline


In [ ]:
clf = Pipeline([
    ("kpca",KernelPCA(n_components=2)),
    ("log_reg",LogisticRegression())
])

param_grid = [
    {
        "kpca_gamma":np.linspace(0.03,0.05,10),
        "kpca__kernel":["rbf","sigmoid"]
    }
]
grid_search = GridSearchCV(clf,param_grid,cv=3)
grid_search.fit(X,y)

In [ ]:
rbf_pca = KernelPCA(n_components=2,Kernel="rbf",gamma=0.0433,fit_inverse_transform=True)
X_reduced = rbf_pca.fit_transform(X)
X_preimage = rbf_pca.inverse_transform(X_reduced)

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(X,X_preimage)


In [ ]:
from sklearn.manifold import LocallyLinearEmbedding
lle = LocallyLinearEmbedding(n_components=2,n_neighbors=10)
X_reduced = lle.fit_transform(X)